# syntax=docker/dockerfile:1
ARG BASE_DIGEST=43180c492a5e6cedd8232e8f77a454f666f247586853eecb90258b26688ad1d3
FROM alpine@sha256:${BASE_DIGEST}

ARG VSFTPD_PORT
ARG VSFTPD_SCRIPT

RUN 	apk update && \
	apk add --no-cache vsftpd \
	gettext \
	shadow 

COPY --chmod=644 ${VSFTPD_SCRIPT}vsftpd.cnf.template /
COPY --chmod=744 ${VSFTPD_SCRIPT}vsftpd_entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
EXPOSE ${VSFTPD_PORT}
CMD ["vsftpd"]
