secrets:
  ftp_password:
    file: ${SECRETS}/ftp_user_password.txt

services:

  nginx:
    extends:
      file: mandatory.yml
      service: nginx
    environment:
      - MODE=bonus
    depends_on:
      - adminer
      - redis
      - vsftpd

  wordpress:
    extends:
      file: mandatory.yml
      service: wordpress
    environment:
      - MODE=bonus

  mariadb:
    extends:
      file: mandatory.yml
      service: mariadb
    environment:
      - MODE=bonus
    
  healthcheck:
    container_name: healthcheck
    build:
      context:
        ${HEALTH_PATH}
      args:
        BASE_DIGEST:      ${ALPINE_DIGEST}
        HEALTH_PORT:      ${HEALTH_PORT}
        HEALTH_SCRIPT:    ${SCRIPTS}
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - MARIADB_PORT=${MARIADB_PORT}
      - WORDPRESS_PORT=${WORDPRESS_PORT}
      - REDIS_PORT=${REDIS_PORT}
      - ADMINER_PORT=${ADMINER_PORT}
      - VSFTPD_PORT=${VSFTPD_PORT}
      - MODE=bonus
    image: healthcheck
    volumes:
      - wp:/var/www/html
    expose:
      - "${HEALTH_PORT}"
    networks:
      - ${NETWORK}
    restart: unless-stopped

  vsftpd:
    container_name: vsftpd
    build:
      context:
        ${VSFTPD_PATH}
      args:
        BASE_DIGEST:      ${ALPINE_DIGEST}
        VSFTPD_PORT:      ${VSFTPD_PORT}
        VSFTPD_SCRIPT:    ${SCRIPTS}
    secrets:
      - ftp_password
    image: vsftpd
    environment:
      - VSFTPD_DATA_PORT=${VSFTPD_DATA_PORT}
      - VSFTPD_PORT=${VSFTPD_PORT}
      - VSFTPD_USER=${VSFTPD_USER}
      - VSFTPD_PASS=/run/secrets/ftp_password
      - MODE=bonus
    ports:
      - "20:20"
      - "${VSFTPD_PORT}:${VSFTPD_PORT}"
      - "5000-5010:5000-5010"
    volumes:
      - wp:/home/${VSFTPD_USER}/ftp/files
    networks:
      - ${NETWORK}
    restart: unless-stopped

  adminer:
    container_name: adminer
    build:
      context:
        ${ADMINER_PATH}
      args:
        BASE_DIGEST:      ${ALPINE_DIGEST}
        ADMINER_PORT:     ${ADMINER_PORT}
        ADMINER_SCRIPT:   ${SCRIPTS}
        PHP_VERSION:      ${PHP_VERSION}
    image: adminer
    environment:
      - ADMINER_VERSION=${ADMINER_VERSION}
      - PHP_VERSION=${PHP_VERSION}
      - MODE=bonus
    expose:
      - "${ADMINER_PORT}"
    volumes:
      - wp:/var/www/html
    networks:
      - ${NETWORK}
    restart: unless-stopped
    depends_on:
      - mariadb

  redis:
     container_name: redis
     build:
       context:
         ${REDIS_PATH}
       args:
         BASE_DIGEST:      ${ALPINE_DIGEST}
         REDIS_PORT:       ${REDIS_PORT}
         REDIS_SCRIPT:     ${SCRIPTS}
     image: redis
     environment:
      - MODE=bonus
     expose:
       - "${REDIS_PORT}"
     networks:
       - ${NETWORK}
     restart: unless-stopped
