# syntax=docker/dockerfile:1
ARG BASE_DIGEST=43180c492a5e6cedd8232e8f77a454f666f247586853eecb90258b26688ad1d3
FROM alpine@sha256:${BASE_DIGEST}

ARG REDIS_PORT
ARG REDIS_SCRIPT

RUN 	apk update && \
	apk add --no-cache redis

COPY --chmod=744 ${REDIS_SCRIPT}redis_entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
EXPOSE ${REDIS_PORT}
CMD ["redis-server"]
