# syntax=docker/dockerfile:1
ARG BASE_DIGEST=43180c492a5e6cedd8232e8f77a454f666f247586853eecb90258b26688ad1d3
FROM alpine@sha256:${BASE_DIGEST}

ARG HEALTH_PORT
ARG HEALTH_SCRIPT

RUN apk update && apk add --no-cache bash curl netcat-openbsd

COPY --chmod=744 ${HEALTH_SCRIPT}health_entrypoint.sh /entrypoint.sh

EXPOSE ${HEALTH_PORT}
ENTRYPOINT ["/entrypoint.sh"]
